#!/usr/bin/env bash
set -e

BASEDIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"
cd "${BASEDIR}"

git add -A
git diff --cached --exit-code &>/dev/null \
    || git commit

git pull

git submodule update --remote

git add -A
git diff --cached --exit-code &>/dev/null \
    || git commit -m "Updated remotes @ $(date -u -Is)"

git push

./setup